version: "3"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./internal/deploy/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U service -d service"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    networks:
      - default
    ports:
      - "8080:8080"
    volumes:
      - ./deployment:/app/config
    command: -config ./config/service.yml
volumes:
  data:
